### ISSUE TITLE
spec-parser run reports errors but exits with `0`

### ISSUE THREAD

**Issue by maxhbr** [spdx/spec-parser#80]
The current spec parser reports an error but does still exit with EXIT_SUCCESS. See for example https://github.com/spdx/spdx-3-model/actions/runs/7118823989/job/19382571564#step:5:25 with the log:
```
 > Run cd spec-parser
WARNING : External property restrictions aren't yet handled properly, they are added to the description of the class.
WARNING : skipping ../model/Core/Properties/_property.md
WARNING : skipping ../model/Core/Vocabularies/_vocab.md
WARNING : External property restrictions aren't yet handled properly, they are added to the description of the class.
WARNING : External property restrictions aren't yet handled properly, they are added to the description of the class.
WARNING : External property restrictions aren't yet handled properly, they are added to the description of the class.
WARNING : External property restrictions aren't yet handled properly, they are added to the description of the class.
WARNING : Overwriting out_dir `/tmp/spec-parser.out`
ERROR   : Invalid Nature attribute in metadata `None`
```

**Comment by goneall** [comment]
In looking at the code, the spec-parser continues to run after the "Error".

Perhaps these are just warnings?

If they are indeed errors - should we stop processing and flag the error?

For the CI, I think it would be useful to report these as errors.

It looks like the methods that log the error all return a `None` value.

If we want to continue execution rather than raise an exception, we can change the return value to an integer which would be a return code - 0 being success.  Then can then be used to set the system level return code.

@zvr @maxhbr - if you agree with the above and would like some help, I can write a PR.

**Comment by bact** [comment]
Does this already resolved in the current version of spec-parser?

**Comment by stevenc-stb** [comment]
I can confirms that it still occur
note from tech meeting from @bact "
We need non-zero exit from the spec-parser, so the GitHub workflow can know that there’s something wrong.

From spec-parser code,
this line detect the error and log it:
https://github.com/spdx/spec-parser/blob/014185824bc0d2080495b66fa1f923935737afaf/spec_parser/model.py#L100-L101 

And maybe this line is trying to check if there's any error in the log and exit(1) if there is:
https://github.com/spdx/spec-parser/blob/014185824bc0d2080495b66fa1f923935737afaf/runparams.py#L23-L24 
But looks like it does not work (or I misunderstood the code flow).

We need non-zero exit from the spec-parser, so the GitHub workflow can know that there’s something wrong."
